export const productActionTypes = {
    FETCH_PRODUCT_REQUEST: "FETCH_PRODUCT_REQUEST",

    FETCH_PRODUCT_REQUEST_SUCCESS: "FETCH_PRODUCT_REQUEST_SUCCESS",

    FETCH_PRODUCT_REQUEST_STATUS: "FETCH_PRODUCT_REQUEST_STATUS",
    
    FETCH_PRODUCT_REQUEST_ERROR: "FETCH_PRODUCT_REQUEST_ERROR",

    REMOVE_SET_SELECTED_PRODUCT: "REMOVE_SET_SELECTED_PRODUCT",

    SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
    
    SET_SHOW_STATUS_TEXT: "SET_SHOW_STATUS_TEXT",
}
