export const cartActionTypes = {
    FETCH_CART_ITEMS: 'FETCH_CART_ITEMS',
    
    FETCH_CART_ITEMS_SUCCESS: "FETCH_CART_ITEMS_SUCCESS",
    
    FETCH_CART_ITEMS_ERROR: "FETCH_CART_ITEMS_ERROR",

    SET_TOTAL_AMOUNT: "SET_TOTAL_AMOUNT",
}

